In [37]:
import numpy as np


In [38]:
np_ink = np.array([[1, 2, 0],[2, 3, 0],[5, 8, 1], [1, 2, 0]])

In [39]:
np_ink[1:, 0:2] -= np_ink[0:-1, 0:2]


In [40]:
np_ink

array([[ 1,  2,  0],
       [ 1,  1,  0],
       [ 3,  5,  1],
       [-4, -6,  0]])

In [41]:
x,y,z = np_ink[:,0], np_ink[:,1], np_ink[:,2]


In [21]:
x

array([ 1,  1,  3, -4])

In [22]:
y

array([ 2,  1,  5, -6])

In [23]:
z

array([0, 0, 1, 0])

In [42]:
x,y,z = np_ink[:,0], np_ink[:,1], np_ink[:,2]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
np_ink = np.array((r, t, z))

In [43]:
np_ink


array([[ 2.23606798,  1.41421356,  5.83095189,  7.21110255],
       [ 1.10714872,  0.78539816,  1.03037683, -2.15879893],
       [ 0.        ,  0.        ,  1.        ,  0.        ]])

In [44]:
np_ink = np.transpose(np_ink)
np_ink

array([[ 2.23606798,  1.10714872,  0.        ],
       [ 1.41421356,  0.78539816,  0.        ],
       [ 5.83095189,  1.03037683,  1.        ],
       [ 7.21110255, -2.15879893,  0.        ]])

In [45]:
np_ink[1:, 0:1] -= np_ink[0:-1, 0:1]



In [46]:
np_ink

array([[ 2.23606798,  1.10714872,  0.        ],
       [-0.82185442,  0.78539816,  0.        ],
       [ 4.41673833,  1.03037683,  1.        ],
       [ 1.38015066, -2.15879893,  0.        ]])